package com.ztuo.modules.house.entity;

import lombok.Data;

import java.util.Date;

@Data
public class LastContact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column last_contact.id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column last_contact.user_id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column last_contact.broker_id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    private Long brokerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column last_contact.remark
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column last_contact.contract_time
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    private Date contractTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column last_contact.id
     *
     * @return the value of last_contact.id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column last_contact.id
     *
     * @param id the value for last_contact.id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column last_contact.user_id
     *
     * @return the value of last_contact.user_id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column last_contact.user_id
     *
     * @param userId the value for last_contact.user_id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column last_contact.broker_id
     *
     * @return the value of last_contact.broker_id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public Long getBrokerId() {
        return brokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column last_contact.broker_id
     *
     * @param brokerId the value for last_contact.broker_id
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public void setBrokerId(Long brokerId) {
        this.brokerId = brokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column last_contact.remark
     *
     * @return the value of last_contact.remark
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column last_contact.remark
     *
     * @param remark the value for last_contact.remark
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column last_contact.contract_time
     *
     * @return the value of last_contact.contract_time
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public Date getContractTime() {
        return contractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column last_contact.contract_time
     *
     * @param contractTime the value for last_contact.contract_time
     *
     * @mbggenerated Mon Feb 10 17:12:42 CST 2020
     */
    public void setContractTime(Date contractTime) {
        this.contractTime = contractTime;
    }
}