package com.ztuo.modules.house.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserHouseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public UserHouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("mobile_phone =", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("mobile_phone <>", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("mobile_phone >", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone >=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("mobile_phone <", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("mobile_phone <=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("mobile_phone like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("mobile_phone not like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIn(List<String> values) {
            addCriterion("mobile_phone in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotIn(List<String> values) {
            addCriterion("mobile_phone not in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("mobile_phone between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("mobile_phone not between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneIsNull() {
            addCriterion("housing_zone is null");
            return (Criteria) this;
        }

        public Criteria andHousingZoneIsNotNull() {
            addCriterion("housing_zone is not null");
            return (Criteria) this;
        }

        public Criteria andHousingZoneEqualTo(String value) {
            addCriterion("housing_zone =", value, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneNotEqualTo(String value) {
            addCriterion("housing_zone <>", value, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneGreaterThan(String value) {
            addCriterion("housing_zone >", value, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneGreaterThanOrEqualTo(String value) {
            addCriterion("housing_zone >=", value, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneLessThan(String value) {
            addCriterion("housing_zone <", value, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneLessThanOrEqualTo(String value) {
            addCriterion("housing_zone <=", value, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneLike(String value) {
            addCriterion("housing_zone like", value, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneNotLike(String value) {
            addCriterion("housing_zone not like", value, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneIn(List<String> values) {
            addCriterion("housing_zone in", values, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneNotIn(List<String> values) {
            addCriterion("housing_zone not in", values, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneBetween(String value1, String value2) {
            addCriterion("housing_zone between", value1, value2, "housingZone");
            return (Criteria) this;
        }

        public Criteria andHousingZoneNotBetween(String value1, String value2) {
            addCriterion("housing_zone not between", value1, value2, "housingZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneIsNull() {
            addCriterion("city_zone is null");
            return (Criteria) this;
        }

        public Criteria andCityZoneIsNotNull() {
            addCriterion("city_zone is not null");
            return (Criteria) this;
        }

        public Criteria andCityZoneEqualTo(String value) {
            addCriterion("city_zone =", value, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneNotEqualTo(String value) {
            addCriterion("city_zone <>", value, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneGreaterThan(String value) {
            addCriterion("city_zone >", value, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneGreaterThanOrEqualTo(String value) {
            addCriterion("city_zone >=", value, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneLessThan(String value) {
            addCriterion("city_zone <", value, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneLessThanOrEqualTo(String value) {
            addCriterion("city_zone <=", value, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneLike(String value) {
            addCriterion("city_zone like", value, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneNotLike(String value) {
            addCriterion("city_zone not like", value, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneIn(List<String> values) {
            addCriterion("city_zone in", values, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneNotIn(List<String> values) {
            addCriterion("city_zone not in", values, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneBetween(String value1, String value2) {
            addCriterion("city_zone between", value1, value2, "cityZone");
            return (Criteria) this;
        }

        public Criteria andCityZoneNotBetween(String value1, String value2) {
            addCriterion("city_zone not between", value1, value2, "cityZone");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIsNull() {
            addCriterion("area_code is null");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIsNotNull() {
            addCriterion("area_code is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCodeEqualTo(String value) {
            addCriterion("area_code =", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotEqualTo(String value) {
            addCriterion("area_code <>", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeGreaterThan(String value) {
            addCriterion("area_code >", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("area_code >=", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLessThan(String value) {
            addCriterion("area_code <", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLessThanOrEqualTo(String value) {
            addCriterion("area_code <=", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLike(String value) {
            addCriterion("area_code like", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotLike(String value) {
            addCriterion("area_code not like", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIn(List<String> values) {
            addCriterion("area_code in", values, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotIn(List<String> values) {
            addCriterion("area_code not in", values, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeBetween(String value1, String value2) {
            addCriterion("area_code between", value1, value2, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotBetween(String value1, String value2) {
            addCriterion("area_code not between", value1, value2, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andFloorInfoIsNull() {
            addCriterion("floor_info is null");
            return (Criteria) this;
        }

        public Criteria andFloorInfoIsNotNull() {
            addCriterion("floor_info is not null");
            return (Criteria) this;
        }

        public Criteria andFloorInfoEqualTo(String value) {
            addCriterion("floor_info =", value, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoNotEqualTo(String value) {
            addCriterion("floor_info <>", value, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoGreaterThan(String value) {
            addCriterion("floor_info >", value, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoGreaterThanOrEqualTo(String value) {
            addCriterion("floor_info >=", value, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoLessThan(String value) {
            addCriterion("floor_info <", value, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoLessThanOrEqualTo(String value) {
            addCriterion("floor_info <=", value, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoLike(String value) {
            addCriterion("floor_info like", value, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoNotLike(String value) {
            addCriterion("floor_info not like", value, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoIn(List<String> values) {
            addCriterion("floor_info in", values, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoNotIn(List<String> values) {
            addCriterion("floor_info not in", values, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoBetween(String value1, String value2) {
            addCriterion("floor_info between", value1, value2, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andFloorInfoNotBetween(String value1, String value2) {
            addCriterion("floor_info not between", value1, value2, "floorInfo");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeIsNull() {
            addCriterion("decorate_type is null");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeIsNotNull() {
            addCriterion("decorate_type is not null");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeEqualTo(String value) {
            addCriterion("decorate_type =", value, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeNotEqualTo(String value) {
            addCriterion("decorate_type <>", value, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeGreaterThan(String value) {
            addCriterion("decorate_type >", value, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("decorate_type >=", value, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeLessThan(String value) {
            addCriterion("decorate_type <", value, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeLessThanOrEqualTo(String value) {
            addCriterion("decorate_type <=", value, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeLike(String value) {
            addCriterion("decorate_type like", value, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeNotLike(String value) {
            addCriterion("decorate_type not like", value, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeIn(List<String> values) {
            addCriterion("decorate_type in", values, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeNotIn(List<String> values) {
            addCriterion("decorate_type not in", values, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeBetween(String value1, String value2) {
            addCriterion("decorate_type between", value1, value2, "decorateType");
            return (Criteria) this;
        }

        public Criteria andDecorateTypeNotBetween(String value1, String value2) {
            addCriterion("decorate_type not between", value1, value2, "decorateType");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdIsNull() {
            addCriterion("attachment_info_id is null");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdIsNotNull() {
            addCriterion("attachment_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdEqualTo(String value) {
            addCriterion("attachment_info_id =", value, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdNotEqualTo(String value) {
            addCriterion("attachment_info_id <>", value, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdGreaterThan(String value) {
            addCriterion("attachment_info_id >", value, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("attachment_info_id >=", value, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdLessThan(String value) {
            addCriterion("attachment_info_id <", value, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdLessThanOrEqualTo(String value) {
            addCriterion("attachment_info_id <=", value, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdLike(String value) {
            addCriterion("attachment_info_id like", value, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdNotLike(String value) {
            addCriterion("attachment_info_id not like", value, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdIn(List<String> values) {
            addCriterion("attachment_info_id in", values, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdNotIn(List<String> values) {
            addCriterion("attachment_info_id not in", values, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdBetween(String value1, String value2) {
            addCriterion("attachment_info_id between", value1, value2, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andAttachmentInfoIdNotBetween(String value1, String value2) {
            addCriterion("attachment_info_id not between", value1, value2, "attachmentInfoId");
            return (Criteria) this;
        }

        public Criteria andLoadTypeIsNull() {
            addCriterion("load_type is null");
            return (Criteria) this;
        }

        public Criteria andLoadTypeIsNotNull() {
            addCriterion("load_type is not null");
            return (Criteria) this;
        }

        public Criteria andLoadTypeEqualTo(String value) {
            addCriterion("load_type =", value, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeNotEqualTo(String value) {
            addCriterion("load_type <>", value, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeGreaterThan(String value) {
            addCriterion("load_type >", value, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeGreaterThanOrEqualTo(String value) {
            addCriterion("load_type >=", value, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeLessThan(String value) {
            addCriterion("load_type <", value, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeLessThanOrEqualTo(String value) {
            addCriterion("load_type <=", value, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeLike(String value) {
            addCriterion("load_type like", value, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeNotLike(String value) {
            addCriterion("load_type not like", value, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeIn(List<String> values) {
            addCriterion("load_type in", values, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeNotIn(List<String> values) {
            addCriterion("load_type not in", values, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeBetween(String value1, String value2) {
            addCriterion("load_type between", value1, value2, "loadType");
            return (Criteria) this;
        }

        public Criteria andLoadTypeNotBetween(String value1, String value2) {
            addCriterion("load_type not between", value1, value2, "loadType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSignLabelIsNull() {
            addCriterion("sign_label is null");
            return (Criteria) this;
        }

        public Criteria andSignLabelIsNotNull() {
            addCriterion("sign_label is not null");
            return (Criteria) this;
        }

        public Criteria andSignLabelEqualTo(String value) {
            addCriterion("sign_label =", value, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelNotEqualTo(String value) {
            addCriterion("sign_label <>", value, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelGreaterThan(String value) {
            addCriterion("sign_label >", value, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelGreaterThanOrEqualTo(String value) {
            addCriterion("sign_label >=", value, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelLessThan(String value) {
            addCriterion("sign_label <", value, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelLessThanOrEqualTo(String value) {
            addCriterion("sign_label <=", value, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelLike(String value) {
            addCriterion("sign_label like", value, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelNotLike(String value) {
            addCriterion("sign_label not like", value, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelIn(List<String> values) {
            addCriterion("sign_label in", values, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelNotIn(List<String> values) {
            addCriterion("sign_label not in", values, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelBetween(String value1, String value2) {
            addCriterion("sign_label between", value1, value2, "signLabel");
            return (Criteria) this;
        }

        public Criteria andSignLabelNotBetween(String value1, String value2) {
            addCriterion("sign_label not between", value1, value2, "signLabel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andWebQuery(){
            addCriterion(" (housing_zone <>'' or city_zone <>'' or address <>'') ");
            return (Criteria) this;
        }


    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_house
     *
     * @mbggenerated do_not_delete_during_merge Sat Feb 15 16:13:37 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_house
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}