package com.ztuo.modules.house.entity;

import lombok.Data;

import java.util.Date;

@Data
public class UygurUserHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.id
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.user_id
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.user_name
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.mobile_phone
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.housing_zone
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String housingZone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.city_zone
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String cityZone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.area_code
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.address
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.floor_info
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String floorInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.area
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.decorate_type
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String decorateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.attachment_info_id
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String attachmentInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.load_type
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String loadType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.status
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.sign_label
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private String signLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uygur_user_house.create_time
     *
     * @mbggenerated Sat Feb 15 16:13:37 CST 2020
     */
    private Date createTime;

}