package com.ztuo.modules.house.service;


import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.ztuo.modules.house.entity.BrokerGuest;
import com.ztuo.modules.house.entity.BrokerGuestExample;
import com.ztuo.modules.house.vo.BrokerGuestVo;

import java.util.List;
import java.util.Map;

public interface IBrokerGuestSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int countByExample(BrokerGuestExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByExample(BrokerGuestExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int save(BrokerGuest record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int saveSelective(BrokerGuest record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    List<BrokerGuest> getByExample(BrokerGuestExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    BrokerGuest getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExampleSelective(BrokerGuest record, BrokerGuestExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExample(BrokerGuest record, BrokerGuestExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKeySelective(BrokerGuest record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table broker_guest
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKey(BrokerGuest record) throws Exception;

    Page<BrokerGuest> pageQuery(BrokerGuestVo queryVo, Map<String, Object> params) throws Exception;
}
