package com.ztuo.modules.house.service;

import com.ztuo.modules.house.entity.DataConfiguration;
import com.ztuo.modules.house.entity.DataConfigurationExample;
import com.ztuo.modules.house.entity.DataConfigurationInfo;

import java.util.List;

public interface IDataConfigurationSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int countByExample(DataConfigurationExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByExample(DataConfigurationExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int save(DataConfiguration record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int saveSelective(DataConfiguration record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    List<DataConfiguration> getByExample(DataConfigurationExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    DataConfiguration getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExampleSelective(DataConfiguration record, DataConfigurationExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExample(DataConfiguration record, DataConfigurationExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKeySelective(DataConfiguration record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table data_configuration
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKey(DataConfiguration record) throws Exception;

    /**
     * 查询全部
     * @return
     */
    List<DataConfiguration> findAll(Long parentNo);


    /**
     * 只获取中文
     * @param parentNo
     * @return
     */
    List<DataConfigurationInfo> getByExampleInfo(Long parentNo);

    /**
     * 只获取维语
     * @param parentNo
     * @return
     */
    List<DataConfigurationInfo> getByExampleInfoWy(Long parentNo);
}
