package com.ztuo.modules.house.service;

import com.ztuo.modules.house.entity.EstateUser;
import com.ztuo.modules.house.entity.EstateUserExample;

import java.util.List;

public interface IEstateUserSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int countByExample(EstateUserExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByExample(EstateUserExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int save(EstateUser record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int saveSelective(EstateUser record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    List<EstateUser> getByExample(EstateUserExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    EstateUser getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExampleSelective(EstateUser record, EstateUserExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExample(EstateUser record, EstateUserExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKeySelective(EstateUser record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_user
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKey(EstateUser record) throws Exception;

    /**
     * 根据手机号查询用户是否存在
     * @param mobilePhone
     * @return
     */
    EstateUser getByPhone(String mobilePhone);
}
