package com.ztuo.modules.house.service;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.ztuo.modules.house.entity.EstateBroker;
import com.ztuo.modules.house.entity.EstateBrokerExample;
import com.ztuo.modules.house.vo.BrokerQuery;

import java.util.List;

public interface IEstateBrokerSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int countByExample(EstateBrokerExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByExample(EstateBrokerExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int save(EstateBroker record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int saveSelective(EstateBroker record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    List<EstateBroker> getByExample(EstateBrokerExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    EstateBroker getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExampleSelective(EstateBroker record, EstateBrokerExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExample(EstateBroker record, EstateBrokerExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKeySelective(EstateBroker record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table estate_broker
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKey(EstateBroker record) throws Exception;

    /**
     * 分页条件查询
     * @param brokerQuery
     * @return
     */
    Page<EstateBroker> pageQueryByCondition(BrokerQuery brokerQuery);
}
