package com.ztuo.modules.house.service;

import com.ztuo.common.utils.RestResponse;
import com.ztuo.modules.house.entity.Feedback;
import com.ztuo.modules.house.entity.FeedbackExample;
import com.ztuo.modules.house.vo.FeedBackQueryVO;

import java.util.List;

public interface IFeedbackSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int countByExample(FeedbackExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int deleteByExample(FeedbackExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int save(Feedback record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int saveSelective(Feedback record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    List<Feedback> getByExample(FeedbackExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    Feedback getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByExampleSelective(Feedback record, FeedbackExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByExample(Feedback record, FeedbackExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByPrimaryKeySelective(Feedback record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table feedback
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByPrimaryKey(Feedback record) throws Exception;

    /**
     * 条件分页查询
     * @param feedBackQueryVO
     * @return
     */
    RestResponse pageQuery(FeedBackQueryVO feedBackQueryVO) throws Exception;
}
