package com.ztuo.modules.house.service;

import com.ztuo.modules.house.entity.HouseCount;
import com.ztuo.modules.house.entity.HouseCountExample;
import com.ztuo.modules.house.entity.HouseCountNews;
import com.ztuo.modules.house.vo.HouseCountVO;
import com.ztuo.modules.sys.entity.SysOrgEntity;

import java.util.List;

public interface IHouseCountSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int countByExample(HouseCountExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int deleteByExample(HouseCountExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int save(HouseCount record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int saveSelective(HouseCount record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    List<HouseCount> getByExample(HouseCountExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    HouseCount getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int updateByExampleSelective(HouseCount record, HouseCountExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int updateByExample(HouseCount record, HouseCountExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int updateByPrimaryKeySelective(HouseCount record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_count
     *
     * @date 2020-03-09 16:41:08
     */
    int updateByPrimaryKey(HouseCount record) throws Exception;

    List<HouseCountNews> getAll(HouseCountVO houseCountVO);

    int saveByOrg(SysOrgEntity sysOrg);

    int addAccount(String estateType,String areaCode);

    int subNewAccount(String areaCode);

    int subRentAccount(String areaCode);

    int subSecondAccount(String areaCode);

    void addAccountByType(String estateType,String areaCode);

    void subAccountByType(String estateType,String areaCode);

    void subAccountByType(String estateType,String areaCode,Integer account);


}
