package com.ztuo.modules.house.service;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.ztuo.modules.house.entity.HouseResource;
import com.ztuo.modules.house.entity.HouseResourceExample;
import com.ztuo.modules.house.vo.HouseCountVO;
import com.ztuo.modules.house.vo.HouseLocationVO;
import com.ztuo.modules.house.vo.HouseResourceVO;

import java.util.List;
import java.util.Map;

public interface IHouseResourceSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int countByExample(HouseResourceExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByExample(HouseResourceExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int save(HouseResource record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int saveSelective(HouseResource record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    List<HouseResource> getByExample(HouseResourceExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    HouseResource getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExampleSelective(HouseResource record, HouseResourceExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByExample(HouseResource record, HouseResourceExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKeySelective(HouseResource record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    int updateByPrimaryKey(HouseResource record) throws Exception;


    /**
     * 分页条件查询上传房源信息
     * @param houseResourceVO
     * @return
     */
    Page<HouseResource> criteriaQuery(HouseResourceVO houseResourceVO, Map<String, Object> params) throws Exception;

    HouseResource findBySignLabel(String signLabel);

    List<HouseLocationVO> getMapLocation(HouseCountVO houseCountVO);
}
