package com.ztuo.modules.house.service;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.ztuo.modules.house.entity.LastContact;
import com.ztuo.modules.house.entity.LastContactExample;
import com.ztuo.modules.house.vo.BaseQueryVo;

import java.util.List;

public interface ILastContactSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int countByExample(LastContactExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int deleteByExample(LastContactExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int save(LastContact record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int saveSelective(LastContact record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    List<LastContact> getByExample(LastContactExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    LastContact getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByExampleSelective(LastContact record, LastContactExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByExample(LastContact record, LastContactExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByPrimaryKeySelective(LastContact record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table last_contact
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByPrimaryKey(LastContact record) throws Exception;

    Page<LastContact> pageQuery(BaseQueryVo queryVo);

    LastContact findByUserIdAndBrokerId(Long userId, Long brokerId);
}
