package com.ztuo.modules.house.service;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.ztuo.modules.house.entity.TbAppVersion;
import com.ztuo.modules.house.entity.TbAppVersionExample;
import com.ztuo.modules.house.vo.BaseQueryVo;

import java.util.List;

public interface ITbAppVersionSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int countByExample(TbAppVersionExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int deleteByExample(TbAppVersionExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int save(TbAppVersion record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int saveSelective(TbAppVersion record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    List<TbAppVersion> getByExample(TbAppVersionExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    TbAppVersion getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int updateByExampleSelective(TbAppVersion record, TbAppVersionExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int updateByExample(TbAppVersion record, TbAppVersionExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int updateByPrimaryKeySelective(TbAppVersion record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table tb_app_version
     *
     * @date 2019-07-13 10:22:13
     */
    int updateByPrimaryKey(TbAppVersion record) throws Exception;

    Page<TbAppVersion> pageQueryByVO(BaseQueryVo queryVO, String appCate);

    List<TbAppVersion> findAppVersionByVersionAndCate(String appVersion, String appCate);

    TbAppVersion findAppVersionByAppCate(String appCate);
}
