package com.ztuo.modules.house.service;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.ztuo.modules.house.entity.UserHouse;
import com.ztuo.modules.house.entity.UserHouseExample;
import com.ztuo.modules.house.vo.UserHouseQuery;

import java.util.List;
import java.util.Map;

public interface IUserHouseSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int countByExample(UserHouseExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int deleteByExample(UserHouseExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int deleteByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int save(UserHouse record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int saveSelective(UserHouse record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    List<UserHouse> getByExample(UserHouseExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    UserHouse getByPrimaryKey(Long parameterId) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByExampleSelective(UserHouse record, UserHouseExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByExample(UserHouse record, UserHouseExample example) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByPrimaryKeySelective(UserHouse record) throws Exception;

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table user_house
     *
     * @date 2020-02-10 16:50:53
     */
    int updateByPrimaryKey(UserHouse record) throws Exception;

    Page<UserHouse> pageQuery(UserHouseQuery houseQuery, Map<String, Object> params) throws Exception;
}
