package com.ztuo.modules.house.service.impl;


import com.ztuo.modules.house.dao.UygurHouseResourceDAO;
import com.ztuo.modules.house.entity.UygurHouseResource;
import com.ztuo.modules.house.entity.UygurHouseResourceExample;
import com.ztuo.modules.house.service.IUygurHouseResourceSV;
import com.ztuo.modules.house.vo.HouseCountVO;
import com.ztuo.modules.house.vo.HouseLocationVO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class UygurHouseResourceSVImpl implements IUygurHouseResourceSV {
    
    @Autowired
    private UygurHouseResourceDAO dao;
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int countByExample(UygurHouseResourceExample example) throws Exception {
    		return dao.countByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int deleteByExample(UygurHouseResourceExample example) throws Exception {
    		return dao.deleteByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int deleteByPrimaryKey(Long parameterId) throws Exception {
    		return dao.deleteByPrimaryKey(parameterId);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int save(UygurHouseResource record) throws Exception {
    		return dao.save(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int saveSelective(UygurHouseResource record) throws Exception {
    		return dao.saveSelective(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public List<UygurHouseResource> getByExample(UygurHouseResourceExample example) throws Exception {
    		return dao.getByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public UygurHouseResource getByPrimaryKey(Long parameterId) throws Exception {
    		return dao.getByPrimaryKey(parameterId);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int updateByExampleSelective(UygurHouseResource record, UygurHouseResourceExample example) throws Exception {
    		return dao.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int updateByExample(UygurHouseResource record, UygurHouseResourceExample example) throws Exception {
    		return dao.updateByExample(record, example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int updateByPrimaryKeySelective(UygurHouseResource record) throws Exception {
    		return dao.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_house_resource
     *
     * @date 2020-02-11 10:05:12
     */
    public int updateByPrimaryKey(UygurHouseResource record) throws Exception {
    		return dao.updateByPrimaryKey(record);
    }

    @Override
    public UygurHouseResource findBySignLabel(String signLabel) {
        return dao.getBySignLabel(signLabel);
    }

    @Override
    public List<HouseLocationVO> getMapLocation(HouseCountVO houseCountVO) {
        List<HouseLocationVO> result = new ArrayList<>();
        UygurHouseResourceExample example = new UygurHouseResourceExample();
        UygurHouseResourceExample.Criteria criteria = example.createCriteria();
        criteria.andAreaCodeEqualTo(houseCountVO.getCityCode());
        if ("0".equals(houseCountVO.getEstateType())){
            criteria.andEstateTypeEqualTo(9);
        }else if ("1".equals(houseCountVO.getEstateType())){
            criteria.andEstateTypeEqualTo(11);
        }else if ("2".equals(houseCountVO.getEstateType())){
            criteria.andEstateTypeEqualTo(10);
        }else {
            return result;
        }
        result = dao.getMapLocation(example);
        return result;
    }
}
