package com.ztuo.modules.house.service.impl;

import com.ztuo.modules.house.dao.UygurFeedbackDAO;
import com.ztuo.modules.house.entity.UygurFeedback;
import com.ztuo.modules.house.entity.UygurFeedbackExample;
import com.ztuo.modules.house.service.IUygurFeedbackSV;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class UygurFeedbackSVImpl implements IUygurFeedbackSV {
    
    @Autowired
    private UygurFeedbackDAO dao;
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int countByExample(UygurFeedbackExample example) throws Exception {
    		return dao.countByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int deleteByExample(UygurFeedbackExample example) throws Exception {
    		return dao.deleteByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int deleteByPrimaryKey(Long parameterId) throws Exception {
    		return dao.deleteByPrimaryKey(parameterId);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int save(UygurFeedback record) throws Exception {
    		return dao.save(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int saveSelective(UygurFeedback record) throws Exception {
    		return dao.saveSelective(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public List<UygurFeedback> getByExample(UygurFeedbackExample example) throws Exception {
    		return dao.getByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public UygurFeedback getByPrimaryKey(Long parameterId) throws Exception {
    		return dao.getByPrimaryKey(parameterId);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int updateByExampleSelective(UygurFeedback record, UygurFeedbackExample example) throws Exception {
    		return dao.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int updateByExample(UygurFeedback record, UygurFeedbackExample example) throws Exception {
    		return dao.updateByExample(record, example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int updateByPrimaryKeySelective(UygurFeedback record) throws Exception {
    		return dao.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table uygur_feedback
     *
     * @date 2020-02-10 16:50:53
     */
    @Override
    public int updateByPrimaryKey(UygurFeedback record) throws Exception {
    		return dao.updateByPrimaryKey(record);
    }
}
